In [3]:
import numpy as np

In [4]:
print(np._version_)
np.show_config() 

AttributeError: module 'numpy' has no attribute '_version_'

In [ ]:
z=np.zeros(10)

In [ ]:
z

In [ ]:
Z = np.zeros((10,10))
print("%d bytes" % (Z.size * Z.itemsize))### how to print size ???

In [ ]:
z=np.zeros(10)
z[4]=1
print(z)

In [ ]:
z=np.arange(10,49)
print(z)

In [ ]:
z=np.arange(50)
z=z[: :-1]
print(z)

In [13]:
z=np.arange(9).reshape(3,3)
print (z)



[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [16]:
nz = np.zeros([1,2,0,0,4,0])
np.nonzero()

(array([], dtype=int64),
 array([], dtype=int64),
 array([], dtype=int64),
 array([], dtype=int64),
 array([], dtype=int64),
 array([], dtype=int64))

In [17]:
Z = np.eye(3)
print(Z)

[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]


In [20]:
ram=np.random.rand(3,3,3)
print (ram)

[[[ 0.9794825   0.09103309  0.55956505]
  [ 0.79718765  0.36424888  0.62833998]
  [ 0.62557646  0.33086068  0.36237237]]

 [[ 0.15789015  0.57426111  0.41905004]
  [ 0.12635365  0.30170577  0.24871743]
  [ 0.54101375  0.02980432  0.72132503]]

 [[ 0.09352095  0.15629504  0.79652303]
  [ 0.10229041  0.0535782   0.62382204]
  [ 0.79857113  0.10792506  0.88196862]]]


In [10]:
minn=np.random.random((3,3,3))
min,max=minn.min(),minn.max()
print(min,max)


0.0160483222624 0.996897202961


In [12]:
meanm=np.arange(0,50)
mm=meanm.mean()
print (mm)

24.5


In [21]:
Z = np.ones((10,10))## how did happen ?
Z[1:-1,1:-1] = 0
print(Z)

[[ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
 [ 1.  0.  0.  0.  0.  0.  0.  0.  1.  1.]
 [ 1.  0.  0.  0.  0.  0.  0.  0.  1.  1.]
 [ 1.  0.  0.  0.  0.  0.  0.  0.  1.  1.]
 [ 1.  0.  0.  0.  0.  0.  0.  0.  1.  1.]
 [ 1.  0.  0.  0.  0.  0.  0.  0.  1.  1.]
 [ 1.  0.  0.  0.  0.  0.  0.  0.  1.  1.]
 [ 1.  0.  0.  0.  0.  0.  0.  0.  1.  1.]
 [ 1.  0.  0.  0.  0.  0.  0.  0.  1.  1.]
 [ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]]


In [22]:
Z = np.ones((5,5))
Z = np.pad(Z, pad_width=1, mode='constant', constant_values=0)###how ??
print(Z)


[[ 0.  0.  0.  0.  0.  0.  0.]
 [ 0.  1.  1.  1.  1.  1.  0.]
 [ 0.  1.  1.  1.  1.  1.  0.]
 [ 0.  1.  1.  1.  1.  1.  0.]
 [ 0.  1.  1.  1.  1.  1.  0.]
 [ 0.  1.  1.  1.  1.  1.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.]]


In [28]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(0.3 == 3 * 0.1)##how 

nan
False
False
nan
False


In [60]:
Z = np.diag(1+np.arange(4),k=-1)
print(Z)

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 1 0 0 0]
 [0 0 2 0 0]
 [0 0 0 3 0]]


In [44]:
Z = np.zeros((8,8),dtype=int)##how 19.
Z[1::2,::2] = 1
Z[::2,1::2] = 1
print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [56]:
np.info

<function numpy.lib.utils.info>

In [24]:
ar=np.arange(3,15).reshape((3,4))

In [25]:
ar

array([[ 3,  4,  5,  6],
       [ 7,  8,  9, 10],
       [11, 12, 13, 14]])

In [27]:
ar[1:-1,1:-1]=0

In [36]:
ar[[0,-1]]=1

In [37]:
ar

array([[ 1,  1,  1,  1],
       [ 7,  0,  0, 10],
       [ 1,  1,  1,  1]])

In [44]:
ar[ :,[0,-1]]=1

In [45]:
ar

array([[1, 1, 1, 1],
       [1, 0, 0, 1],
       [1, 1, 1, 1]])

In [46]:
ar=np.arange(1,13).reshape((3,4))

In [47]:
ar

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [54]:
np.pad(ar,1,mode='constant', constant_values=0)

array([[ 0,  0,  0,  0,  0,  0],
       [ 0,  1,  2,  3,  4,  0],
       [ 0,  5,  6,  7,  8,  0],
       [ 0,  9, 10, 11, 12,  0],
       [ 0,  0,  0,  0,  0,  0]])