In [15]:
import numpy as np

In [16]:
print(np._version_)
np.show_config() 

AttributeError: module 'numpy' has no attribute '_version_'

In [18]:
z=np.zeros(10)

In [19]:
z

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])

In [21]:
Z = np.zeros((10,10))
print("%d bytes" % (Z.size * Z.itemsize))### how to print size ???

800 bytes


In [24]:
z=np.zeros(10)
z[4]=1
print(z)

[ 0.  0.  0.  0.  1.  0.  0.  0.  0.  0.]


In [31]:
z=np.arange(10,49)
print(z)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34
 35 36 37 38 39 40 41 42 43 44 45 46 47 48]


In [44]:
z=np.arange(50)
z=z[: :-1]
print(z)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26 25
 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2  1  0]


In [51]:
z=np.arange(9).reshape(3,3)
print (z)



[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [54]:
nz = np.zeros([1,2,0,0,4,0])
print(nz) ### how to find non zero 

[]


In [58]:
Z = np.eye(3)
print(Z)

[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]


In [64]:
ram=np.random.random((3,3,3))
print (ram)

[[[ 0.93825128  0.64530001  0.3176815 ]
  [ 0.08432159  0.09767448  0.90384888]
  [ 0.15286106  0.87240543  0.61334552]]

 [[ 0.61591264  0.98050255  0.55815442]
  [ 0.92419364  0.09879834  0.02827507]
  [ 0.35421315  0.55950678  0.18698649]]

 [[ 0.85934051  0.93511383  0.36662131]
  [ 0.30740059  0.61030093  0.83190544]
  [ 0.68655226  0.79543717  0.28369161]]]
