In [7]:
import numpy as np

In [8]:
print(np._version_)
np.show_config() 

AttributeError: module 'numpy' has no attribute '_version_'

In [9]:
z=np.zeros(10)

In [10]:
z

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])

In [11]:
Z = np.zeros((10,10))
print("%d bytes" % (Z.size * Z.itemsize))### how to print size ???

800 bytes


In [12]:
z=np.zeros(10)
z[4]=1
print(z)

[ 0.  0.  0.  0.  1.  0.  0.  0.  0.  0.]


In [13]:
z=np.arange(10,49)
print(z)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34
 35 36 37 38 39 40 41 42 43 44 45 46 47 48]


In [14]:
z=np.arange(50)
z=z[: :-1]
print(z)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26 25
 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2  1  0]


In [15]:
z=np.arange(9).reshape(3,3)
print (z)



[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [16]:
nz = np.zeros([1,2,0,0,4,0])
print(nz) ### how to find non zero  10.

[]


In [17]:
Z = np.eye(3)
print(Z)

[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]


In [ ]:
ram=np.random.random((3,3,3))
print (ram)

In [10]:
minn=np.random.random((3,3,3))
min,max=minn.min(),minn.max()
print(min,max)


0.0160483222624 0.996897202961


In [12]:
meanm=np.arange(0,50)
mm=meanm.mean()
print (mm)

24.5


In [21]:
Z = np.ones((10,10))## how did happen ?
Z[1:-1,1:-1] = 0
print(Z)

[[ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
 [ 1.  0.  0.  0.  0.  0.  0.  0.  1.  1.]
 [ 1.  0.  0.  0.  0.  0.  0.  0.  1.  1.]
 [ 1.  0.  0.  0.  0.  0.  0.  0.  1.  1.]
 [ 1.  0.  0.  0.  0.  0.  0.  0.  1.  1.]
 [ 1.  0.  0.  0.  0.  0.  0.  0.  1.  1.]
 [ 1.  0.  0.  0.  0.  0.  0.  0.  1.  1.]
 [ 1.  0.  0.  0.  0.  0.  0.  0.  1.  1.]
 [ 1.  0.  0.  0.  0.  0.  0.  0.  1.  1.]
 [ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]]


In [22]:
Z = np.ones((5,5))
Z = np.pad(Z, pad_width=1, mode='constant', constant_values=0)###how ??
print(Z)


[[ 0.  0.  0.  0.  0.  0.  0.]
 [ 0.  1.  1.  1.  1.  1.  0.]
 [ 0.  1.  1.  1.  1.  1.  0.]
 [ 0.  1.  1.  1.  1.  1.  0.]
 [ 0.  1.  1.  1.  1.  1.  0.]
 [ 0.  1.  1.  1.  1.  1.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.]]


In [28]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(0.3 == 3 * 0.1)##how 

nan
False
False
nan
False


In [38]:
Z = np.diag(1+np.arange(4),k=-1)
print(Z)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


In [44]:
Z = np.zeros((8,8),dtype=int)##how 19.
Z[1::2,::2] = 1
Z[::2,1::2] = 1
print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]
