 
 # Data science 
 ### WHAT IS DATE SCIENCE 
- ANALYSTS/VISULIZATION .MACHINE LEARNING ?
 
 ## References for requirement 
 
 

mumpy array is for fasr array 

In [3]:
import numpy as np

In [4]:
import os

In [5]:
os.path.join


<function ntpath.join>

In [6]:
np.array([1, 1.3,6])

array([ 1. ,  1.3,  6. ])

In [9]:
np.array([[1,4,5,6,7],[3,4,5,6,3]])

array([[1, 4, 5, 6, 7],
       [3, 4, 5, 6, 3]])

In [10]:
np.arange(0,5)

array([0, 1, 2, 3, 4])

In [17]:
np.arange(0,18) . reshape((2,3,3))

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]]])

In [18]:
np.arange(0,100)*2

array([  0,   2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,
        26,  28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,
        52,  54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,
        78,  80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100, 102,
       104, 106, 108, 110, 112, 114, 116, 118, 120, 122, 124, 126, 128,
       130, 132, 134, 136, 138, 140, 142, 144, 146, 148, 150, 152, 154,
       156, 158, 160, 162, 164, 166, 168, 170, 172, 174, 176, 178, 180,
       182, 184, 186, 188, 190, 192, 194, 196, 198])

In [19]:
help(tw)

NameError: name 'tw' is not defined