In [17]:
import numpy as np

In [18]:
np.array ([1,3,4,5,6])

array([1, 3, 4, 5, 6])

In [30]:
lst=[1.3,4,5,6]

In [31]:
nplst=np.array(lst)

In [32]:
type(lst)

list

In [33]:
nplst

array([ 1.3,  4. ,  5. ,  6. ])

In [34]:
nplst.size

4

In [35]:
nplst.ndim


1

In [36]:
dir(np)

['ALLOW_THREADS',
 'BUFSIZE',
 'CLIP',
 'ComplexWarning',
 'DataSource',
 'ERR_CALL',
 'ERR_DEFAULT',
 'ERR_IGNORE',
 'ERR_LOG',
 'ERR_PRINT',
 'ERR_RAISE',
 'ERR_WARN',
 'FLOATING_POINT_SUPPORT',
 'FPE_DIVIDEBYZERO',
 'FPE_INVALID',
 'FPE_OVERFLOW',
 'FPE_UNDERFLOW',
 'False_',
 'Inf',
 'Infinity',
 'MAXDIMS',
 'MAY_SHARE_BOUNDS',
 'MAY_SHARE_EXACT',
 'MachAr',
 'ModuleDeprecationWarning',
 'NAN',
 'NINF',
 'NZERO',
 'NaN',
 'PINF',
 'PZERO',
 'PackageLoader',
 'RAISE',
 'RankWarning',
 'SHIFT_DIVIDEBYZERO',
 'SHIFT_INVALID',
 'SHIFT_OVERFLOW',
 'SHIFT_UNDERFLOW',
 'ScalarType',
 'Tester',
 'TooHardError',
 'True_',
 'UFUNC_BUFSIZE_DEFAULT',
 'UFUNC_PYVALS_NAME',
 'VisibleDeprecationWarning',
 'WRAP',
 '_NoValue',
 '__NUMPY_SETUP__',
 '__all__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__doc__',
 '__file__',
 '__git_revision__',
 '__loader__',
 '__mkl_version__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_distributor_init',
 '_globals',
 '_import

In [27]:
np.arrary

list

In [28]:
ar=np.arange(2,30)

In [40]:
ar

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [41]:
nplst2=ar([[1,3], [1,2]])


TypeError: 'numpy.ndarray' object is not callable

In [42]:
ar

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [43]:
nplst

array([ 1.3,  4. ,  5. ,  6. ])

In [51]:
np.arange(0,21).reshape((1,3,7)) ## 1 is depth, 3 is rwo and 7 is colum and bracket determine the deminsion 

array([[[ 0,  1,  2,  3,  4,  5,  6],
        [ 7,  8,  9, 10, 11, 12, 13],
        [14, 15, 16, 17, 18, 19, 20]]])

In [56]:
nplst3=np.arange(0,24).reshape((2,3,4)) 

In [57]:
nplst3

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [61]:
nplst4=np.arange(0,120). reshape((2,3,4,5))

In [62]:
nplst4

array([[[[  0,   1,   2,   3,   4],
         [  5,   6,   7,   8,   9],
         [ 10,  11,  12,  13,  14],
         [ 15,  16,  17,  18,  19]],

        [[ 20,  21,  22,  23,  24],
         [ 25,  26,  27,  28,  29],
         [ 30,  31,  32,  33,  34],
         [ 35,  36,  37,  38,  39]],

        [[ 40,  41,  42,  43,  44],
         [ 45,  46,  47,  48,  49],
         [ 50,  51,  52,  53,  54],
         [ 55,  56,  57,  58,  59]]],


       [[[ 60,  61,  62,  63,  64],
         [ 65,  66,  67,  68,  69],
         [ 70,  71,  72,  73,  74],
         [ 75,  76,  77,  78,  79]],

        [[ 80,  81,  82,  83,  84],
         [ 85,  86,  87,  88,  89],
         [ 90,  91,  92,  93,  94],
         [ 95,  96,  97,  98,  99]],

        [[100, 101, 102, 103, 104],
         [105, 106, 107, 108, 109],
         [110, 111, 112, 113, 114],
         [115, 116, 117, 118, 119]]]])

In [63]:
r1=np.random.random(50)

In [64]:
r1

array([ 0.14271169,  0.55801115,  0.35851997,  0.39136967,  0.86941415,
        0.28353251,  0.03436611,  0.07479096,  0.75635418,  0.03833137,
        0.49853536,  0.18803105,  0.57735868,  0.57760035,  0.63092891,
        0.53636338,  0.89454958,  0.78767601,  0.27450212,  0.22469366,
        0.72345861,  0.97986201,  0.51004172,  0.64649491,  0.1766    ,
        0.45500491,  0.55900023,  0.89038908,  0.04204457,  0.85071986,
        0.38268986,  0.28315634,  0.27512212,  0.44876291,  0.27986828,
        0.5679427 ,  0.45126877,  0.09921618,  0.7619112 ,  0.01092135,
        0.27519483,  0.45166529,  0.6729152 ,  0.09448773,  0.98084303,
        0.49219514,  0.65300577,  0.74986034,  0.83905884,  0.15789792])

In [67]:
r1.sum()

23.459240548943352

In [68]:
r1.cumsum()

array([  0.14271169,   0.70072284,   1.05924282,   1.45061249,
         2.32002664,   2.60355915,   2.63792526,   2.71271621,
         3.46907039,   3.50740176,   4.00593712,   4.19396817,
         4.77132684,   5.3489272 ,   5.9798561 ,   6.51621948,
         7.41076906,   8.19844507,   8.47294718,   8.69764084,
         9.42109945,  10.40096146,  10.91100318,  11.55749809,
        11.73409808,  12.18910299,  12.74810322,  13.6384923 ,
        13.68053687,  14.53125673,  14.9139466 ,  15.19710293,
        15.47222506,  15.92098796,  16.20085625,  16.76879894,
        17.22006772,  17.3192839 ,  18.0811951 ,  18.09211645,
        18.36731129,  18.81897658,  19.49189178,  19.58637951,
        20.56722254,  21.05941768,  21.71242345,  22.46228379,
        23.30134263,  23.45924055])

In [69]:
r4=np.random.randint(10,30,size=25)

In [70]:
r4

array([28, 15, 23, 12, 10, 26, 12, 19, 27, 29, 21, 24, 18, 25, 16, 28, 29,
       10, 25, 16, 14, 13, 17, 21, 18])

In [71]:
r4.mean()

19.84

In [74]:
np.median(r4)

19.0

In [75]:
np.var(r4)

37.57439999999999

In [76]:
mean=r4.mean()

In [78]:
mean

19.84

In [82]:
meandiff=r4-mean

In [83]:
meandiff

array([ 8.16, -4.84,  3.16, -7.84, -9.84,  6.16, -7.84, -0.84,  7.16,
        9.16,  1.16,  4.16, -1.84,  5.16, -3.84,  8.16,  9.16, -9.84,
        5.16, -3.84, -5.84, -6.84, -2.84,  1.16, -1.84])

In [86]:
r4

array([28, 15, 23, 12, 10, 26, 12, 19, 27, 29, 21, 24, 18, 25, 16, 28, 29,
       10, 25, 16, 14, 13, 17, 21, 18])

In [89]:
r4

array([28, 15, 23, 12, 10, 26, 12, 19, 27, 29, 21, 24, 18, 25, 16, 28, 29,
       10, 25, 16, 14, 13, 17, 21, 18])

In [88]:
r4

range(0, 3)

In [103]:
r4=np.append(r4,17)

In [104]:
len(r4)

26

In [105]:
r41,r42= np.split(r4,2)

In [106]:
r41

array([28, 15, 23, 12, 10, 26, 12, 19, 27, 29, 21, 24, 18])

In [109]:
np.linspace(1,20,num=16)

array([  1.        ,   2.26666667,   3.53333333,   4.8       ,
         6.06666667,   7.33333333,   8.6       ,   9.86666667,
        11.13333333,  12.4       ,  13.66666667,  14.93333333,
        16.2       ,  17.46666667,  18.73333333,  20.        ])