In [4]:
import numpy as np 

In [5]:
ar1=np.arange(0,12)



In [6]:
ar1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [7]:
ar1[1]

1

In [8]:
ar1[2:7]

array([2, 3, 4, 5, 6])

In [9]:
ar1[2:9:2]##LAST KO 2 differece 

array([2, 4, 6, 8])

In [10]:
lst=list(range(0,12))

In [11]:
ar2=np.arange(0,12).reshape((3,4))### multidimensional slices

In [12]:
ar2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [13]:
ar2[1]

array([4, 5, 6, 7])

In [14]:
ar2[1][1]

5

In [15]:
ar2[1,1]# 1 st represt the first col another row  get 5  

5

In [16]:
ar2[0:2,0:2]

array([[0, 1],
       [4, 5]])

In [17]:
ar2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [18]:
ar2[::2,1:3]

array([[ 1,  2],
       [ 9, 10]])

In [19]:
ar2[::2,::3]

array([[ 0,  3],
       [ 8, 11]])

In [20]:
####ar2[[0,1],::2] 

In [21]:
arr3=np.arange(0,24).reshape((2,3,4))

In [22]:
arr3

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [23]:
arr3[: ,0,::2]

array([[ 0,  2],
       [12, 14]])

In [24]:
### masking and bollean array 

In [25]:
mask=np.array ([True,False,True,True])

In [26]:
mask

array([ True, False,  True,  True], dtype=bool)

In [27]:
arr12=np.arange(1,15)

In [28]:
arr12

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [29]:
arr12 / 3 < 2

array([ True,  True,  True,  True,  True, False, False, False, False,
       False, False, False, False, False], dtype=bool)

In [30]:
arr12[arr12 / 3 < 2]

array([1, 2, 3, 4, 5])

In [31]:
ar1


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [32]:
ar2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [53]:
ar2[::2,1:4:]

array([[ 1,  2,  3],
       [ 9, 10, 11]])

In [54]:
arr3 = np.arange(0, 24).reshape((2, 3, 4))

In [55]:
arr3

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [90]:
arr3[:, :2, [1, 2]]

array([[[ 1,  2],
        [ 5,  6]],

       [[13, 14],
        [17, 18]]])